SELECT B.USER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
FROM (SELECT WRITER_ID, PRICE FROM USED_GOODS_BOARD WHERE STATUS = 'DONE') A
JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID 
GROUP BY NICKNAME HAVING SUM(A.PRICE) >= 700000 ORDER BY TOTAL_SALES;